import {Button} from '@/components/ui/button';
import {challenges,finalProofGroups,type TaskId} from '@/lib/game/case';
import {archiveComplete,corrections,heardNode,recapNodes} from '@/lib/game/epilogue';
import {script,displayText} from '@/lib/game/script';
import type {GameState,Tool,InvestigationAction} from '@/lib/game/state';

export function ArchivePanel({state,detail,dispatch}:{state:GameState;detail:string|null;dispatch:React.Dispatch<InvestigationAction>}){
 const show=(s:string)=>displayText(s,state.playerName);
 const open=(tool:Tool,id:string|null=null)=>{dispatch({type:'view',tool});if(id)dispatch({type:'viewState',patch:{detail:id}});};
 if(!archiveComplete(state))return <p>마지막 대화를 마치면 이번 사건의 기록 보관함이 열립니다.</p>;
 if(detail==='archive:credits')return <article><h3 className="detail-title">크레딧</h3><p>여울관: 남겨 둔 자리</p><p>기획·구조 설계·편집·구현: Codex를 사용한 제작</p><p>한국어 대본: ChatGPT 작성 원고를 검토·편집한 수용본</p><p>인물·장소 그림: OpenAI 이미지 생성 도구로 제작하고 장면 설정에 맞춰 검토한 삽화</p><p>증거 문서·도면·실험 화면: 원문과 치수에 따른 문자·벡터 구성</p><p>음성: Microsoft Heami Desktop 합성 음성. 효과음: 프로그램으로 제작한 소리. 실제 인물을 녹음한 음성이 아닙니다.</p><p>화면: React · Radix UI · Tailwind CSS · Lucide</p><p>이 작품의 인물과 사건은 허구입니다.</p></article>;
 if(detail==='archive:recap')return <article><h3 className="detail-title">이번 선택의 회고</h3>{recapNodes(state.choices).filter(n=>state.log.some(l=>l.nodeId===n.id)).map(n=><p className="archive-card" key={n.id}>{show(n.text)}</p>)}</article>;
 if(detail==='archive:corrections')return <div><h3 className="detail-title">실제로 들은 진술의 변화</h3>{corrections.filter(c=>heardNode(state,c.before)&&heardNode(state,c.after)).map(c=><article className="archive-card" key={c.id}><h4>{script.evidence[c.evidence].title}</h4><div className="correction-pair"><section><h5>처음 한 말</h5><p>{show(heardNode(state,c.before)!.text)}</p></section><section><h5>이후 정정</h5><p>{show(heardNode(state,c.after)!.text)}</p></section></div><Button onClick={()=>open('evidence',c.evidence)}>정정 기록 원문</Button><Button variant="outline" onClick={()=>open('history',script.utterances[c.before].scene)}>처음 들은 자리</Button><Button variant="outline" onClick={()=>open('history',script.utterances[c.after].scene)}>정정한 자리</Button></article>)}</div>;
 if(detail==='archive:proofs')return <div><h3 className="detail-title">성공한 추론과 당시 제출문</h3>{state.investigation!.knowledge.map(k=>{
  const id=(k.startsWith('KQ')?k.slice(1):k.replace('K','D')) as TaskId,d=state.investigation!.drafts[id],c=challenges[id];
  return <article className="archive-card" key={id}><h4>{script.scenes[`C_${id}`].title}</h4>{d?<><dl>{c.fields.map(f=><div key={f.id}><dt>{f.label}</dt><dd>{f.options.find(o=>o.value===d.fields[f.id])?.label}</dd></div>)}</dl>{d.evidence.map(e=><Button key={e} variant="outline" onClick={()=>open('evidence',e)}>{script.evidence[e].title}</Button>)}{id==='D30'&&finalProofGroups.map(g=><section className="archive-role" key={g.id}><h5>{g.label}</h5>{d.roleEvidence?.[g.id]?.map(e=><Button key={e} variant="outline" onClick={()=>open(e.startsWith('E')?'evidence':'history',e.startsWith('E')?e:e.startsWith('KQ')?`C_${e.slice(1)}`:`C_D${e.slice(1)}`)}>{e.startsWith('E')?script.evidence[e].title:script.scenes[e.startsWith('KQ')?`C_${e.slice(1)}`:`C_D${e.slice(1)}`].title}</Button>)}{d.roleNotes?.[g.id]&&<p className="archive-note">{d.roleNotes[g.id]}</p>}</section>)}{d.note&&<p className="archive-note">당시 메모: {d.note}</p>}</>:<p>이 저장에는 당시 제출문의 별도 초안이 없습니다.</p>}<Button onClick={()=>open('history',`C_${id}`)}>실제 추론 대화 다시 읽기</Button></article>;
 })}</div>;
 return <section className="archive-home"><h3 className="detail-title">사건 보관함</h3><p>{state.evidence.length}개 자료 · {state.investigation!.knowledge.length}개 입증한 결론 · 이번에 지나온 대화와 선택</p><div className="archive-menu">{[['evidence','증거 보관함',null],['archive','추론 기록','archive:proofs'],['archive','진술 변화','archive:corrections'],['history','대화 기록',null],['archive','선택 회고','archive:recap'],['settings','저장·설정',null],['archive','크레딧','archive:credits']].map(([tool,label,id])=><Button variant="outline" key={label} onClick={()=>open(tool as Tool,id)}>{label}</Button>)}</div><p>기록을 다시 읽어도 사건의 선택과 결론은 바뀌지 않습니다. 새 이야기는 저장·설정에서 별도 슬롯으로 시작할 수 있습니다.</p></section>;
}
