export function ReadableOriginal(){return <figure className="readable-original"><div className="bound-book"><span className="binding-stitch" aria-hidden>┆<br/>┆<br/>┆</span><div><strong>같은 제본의 하단 본장 · 펼쳐 확인</strong><dl><div><dt>접수</dt><dd>20:14</dd></div><div><dt>종료</dt><dd>20:24</dd></div><div><dt>입회</dt><dd>목백로</dd></div><div><dt>참여</dt><dd>탁두철 · 배한술</dd></div><div><dt>임금액</dt><dd><span className="redacted-amount" aria-label="합의한 금액 가림"/></dd></div></dl></div></div><figcaption>하단 본장은 떼지 않고 받침 위에서 펼쳤습니다. 원본은 호숫가 보관 창고에 남습니다.</figcaption></figure>;}
export function BindingConnections(){return <figure className="binding-connections"><h4>같은 본장의 연결부</h4><ol><li>끊기지 않은 제본 실</li><li>앞뒤 장과 이어지는 연속 번호</li><li>상단 절취부와 하단 본장의 맞물림</li><li>접수 당시의 접힘·표지와 개봉 사진 대조</li></ol><figcaption>동일한 물건의 물리적 연속성 · 시계 정확성과 편집자 신원은 별도로 확인합니다.</figcaption></figure>;}
export function ImprintTest(){return <figure className="imprint-test"><h4>두 겹 시각 인상 시험</h4><div className="imprint-plies"><div>느슨한 상단 인계지<br/><strong>접수·종료 고정 필드</strong></div><div>제본된 하단 본장<br/><strong>같은 고정 필드에 함께 인상</strong></div></div><p>시각 인상 장치에서 같은 값이 두 겹에 남습니다. 주방의 일반 복사기는 이미 적힌 면을 복사합니다.</p><figcaption>오늘의 재현시험 · 어제의 독립 목격이 아니며 장치의 절대적 무오류를 뜻하지 않습니다.</figcaption></figure>;}
export function CopyOverlay(){return <figure className="copy-overlay"><h4>같은 작업 번호·같은 필드 대조</h4><table><thead><tr><th>필드</th><th>하단 원본</th><th>공개 사본</th></tr></thead><tbody><tr><th>접수</th><td>20:14</td><td>20:07</td></tr><tr><th>종료</th><td>20:24</td><td>20:17</td></tr><tr><th>임금액</th><td colSpan={2}>합의한 위치의 가림</td></tr></tbody></table><p>두 시각 필드 각각 −7분 · 숫자 기준선은 인상 위치와 어긋남</p><figcaption>정상적인 임금액 가림과 별개의 시각 변경입니다. 이 대조만으로 편집자를 식별하지 않습니다.</figcaption></figure>;}
export function ObservationBands(){return <figure className="observation-bands"><svg viewBox="0 0 620 260" role="img" aria-label="원본 인계 20시 14분부터 24분. 시계 오차 1분을 적용한 최소 연속 관찰 15분부터 23분이 사건 범위 17분부터 21분을 포함한다.">
  {[14,15,17,19,21,23,24].map(m=><g key={m}><line x1={60+(m-14)*50} x2={60+(m-14)*50} y1="35" y2="218" stroke="#82927c" strokeDasharray="3 5"/><text x={60+(m-14)*50} y="243" textAnchor="middle">:{m}</text></g>)}
  <rect x="60" y="42" width="500" height="42" fill="#ded4b8"/><text x="310" y="70" textAnchor="middle">원본 인계 20:14–20:24</text>
  <rect x="110" y="101" width="400" height="42" fill="#b8cbb5"/><text x="310" y="129" textAnchor="middle">최소 연속 관찰 20:15–20:23</text>
  <rect x="210" y="160" width="200" height="42" fill="#d3af87"/><text x="310" y="188" textAnchor="middle">사건 20:17–20:21</text>
  </svg><figcaption>목백로의 직접 연속 관찰 + 인증된 본장 + 시계 오차. 사건 구간의 행위자 설명을 배제하며 외투 조기 인계 자체의 불가능을 뜻하지 않습니다.</figcaption></figure>;}
