import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {displayText,script} from '@/lib/game/script';
import type {GameState,Tool,View} from '@/lib/game/state';
import {personName} from '@/lib/game/evidence-index';
import {portraitPath} from '@/lib/game/art';
import {conversations,defaultHistoryFilters,historyFilterOptions,historyGroups,modeNames,personRecord,recordContext,recordNode,type HistoryFilters,type LogEntry} from '@/lib/game/record-index';

type Props={state:GameState;detail:string|null;inspect:(tool:Tool,id:string)=>void};
const correctionLabels:Record<string,string>={Q01:'이후 정정된 목격 보기',Q02:'이후 재생 조작 정정 보기',Q03:'이후 반출 경로 정정 보기',Q04:'이후 직원 동의 범위 정정 보기',Q05:'이후 창 목격 정정 보기',Q06:'이후 복사 감독 범위 정정 보기'};
function Context({entry}:{entry:LogEntry}){const c=recordContext(entry);return <p className="record-context">{c.time} · {c.place}{!entry.origin&&<span> · 이 저장에는 당시 위치 정보가 없습니다.</span>}{c.mode!=='direct'&&<span> · {modeNames[c.mode]} · 장소는 듣는 쪽 기준</span>}</p>;}
function Excerpt({entry,state,inspect,section}:{entry:LogEntry;state:GameState;inspect:Props['inspect'];section:string}){
 const n=recordNode(entry);return <div className="record-excerpt"><Context entry={entry}/>{n.speaker&&<p className="record-attribution">{personName(n.speaker,state.playerName)} · {n.label&&!/^P\d/.test(n.label)?n.label:modeNames[recordContext(entry).mode]}</p>}<p className={n.kind==='direction'?'stage-direction':''}>{displayText(n.text,state.playerName)}</p><Button id={`record-${section}-${n.id}`} variant="ghost" onClick={()=>inspect('history',entry.sceneId)}>{script.scenes[entry.sceneId].title} · 대화 원문</Button></div>;
}

export function HistoryPanel({state,detail,inspect,search,onSearch,replayIndex,onReplay,filters=defaultHistoryFilters,onFilters}:Props&{search:string;onSearch:(s:string)=>void;replayIndex?:number;onReplay?:(n:number|undefined)=>void;filters?:HistoryFilters;onFilters:(f:HistoryFilters)=>void}){
 const all=conversations(state),selected=all.find(c=>c.id===detail),filtered=conversations(state,search,filters),options=historyFilterOptions(state);
 const show=(text:string)=>displayText(text,state.playerName).replace(/^Objective:\s*/,'');
 const replay=selected?.entries.filter(l=>recordNode(l).kind!=='evidence')??[];
 if(selected&&replayIndex!==undefined&&replay.length){const index=Math.min(replayIndex,replay.length-1),entry=replay[index],n=recordNode(entry);return <section className="history-replay"><h3 className="detail-title">{selected.title}</h3><p>이번에 지나온 대화 다시 읽기 · {index+1}/{replay.length}</p><Context entry={entry}/>{n.speaker&&<strong>{personName(n.speaker,state.playerName)} · {n.label&&!/^P\d/.test(n.label)?n.label:modeNames[recordContext(entry).mode]}</strong>}<p className={n.kind==='direction'?'stage-direction':''}>{show(n.text)}</p><div className="task-actions"><Button variant="outline" disabled={index===0} onClick={()=>onReplay?.(index-1)}>이전 대사</Button><Button disabled={index===replay.length-1} onClick={()=>onReplay?.(index+1)}>다음 대사</Button><Button variant="ghost" onClick={()=>onReplay?.(undefined)}>전문으로 보기</Button></div></section>;}
 if(selected){const acquired=[...new Set(selected.entries.map(recordNode).filter(n=>n.kind==='evidence'&&n.evidenceId&&state.evidence.includes(n.evidenceId)).map(n=>n.evidenceId!))];return <div className="history-log"><Button onClick={()=>onReplay?.(0)}>한 대사씩 다시 읽기</Button><h3 className="detail-title">{selected.title}</h3><p className="source-caption">지난 대화 · 실제로 선택하고 들은 내용만 표시합니다.</p><p>기록에 등장한 목소리: {selected.participants.map(p=>personName(p,state.playerName)).join(' · ')||'아직 없음'}</p>
  {!!acquired.length&&<div className="task-actions" aria-label="이 장면에서 확인한 자료">{acquired.map(e=><Button id={`history-evidence-${e}`} key={e} variant="outline" onClick={()=>inspect('evidence',e)}>{script.evidence[e].title}</Button>)}</div>}
  {selected.entries.map((entry,index)=>{const n=recordNode(entry);if(n.kind==='evidence')return null;const previous=index?recordContext(selected.entries[index-1]):null,c=recordContext(entry);const correction=n.speaker?personRecord(state,n.speaker)?.corrections.find(q=>q.before===n.id&&q.corrected):null;return <div key={n.id+index} className="history-entry">{(!previous||previous.place!==c.place||previous.time!==c.time||previous.mode!==c.mode)&&<Context entry={entry}/>}<p className={n.kind==='direction'?'stage-direction':''}>{n.kind==='speech'&&<strong>{n.speaker?personName(n.speaker,state.playerName):n.label}{n.label&&!/^P\d/.test(n.label)?` · ${n.label}`:''}</strong>}{show(n.text)}</p>{correction&&<Button id={`history-correction-${correction.id}`} variant="outline" onClick={()=>inspect('evidence',correction.evidence)}>{correctionLabels[correction.id]}</Button>}</div>;})}</div>;}
 return <section aria-label="대화 기록 목록"><Input id="history-search" aria-label="대화 검색" placeholder="종류·인물·장소·대화에서 찾기" value={search} onChange={e=>onSearch(e.target.value)}/><div className="record-filters"><label>종류<select id="history-group" value={filters.group} onChange={e=>onFilters({...filters,group:e.target.value as HistoryFilters['group']})}><option value="">모든 대화</option>{options.groups.map(g=><option key={g} value={g}>{historyGroups[g]}</option>)}</select></label><label>화자<select id="history-speaker" value={filters.speaker} onChange={e=>onFilters({...filters,speaker:e.target.value})}><option value="">모든 화자</option>{options.speakers.map(p=><option key={p} value={p}>{personName(p,state.playerName)}</option>)}</select></label></div>
 {!!filters.speaker&&<p className="record-context">화자: {personName(filters.speaker,state.playerName)}</p>}<div className="evidence-results"><p role="status">기록 {all.length}개 중 {filtered.length}개</p>{!!(search||filters.group||filters.speaker)&&<Button id="history-reset" variant="ghost" onClick={()=>{onSearch('');onFilters({...defaultHistoryFilters});}}>조건 초기화</Button>}</div>
 {options.groups.map(g=>{const rows=filtered.filter(c=>c.group===g);return !!rows.length&&<section className="history-group" key={g}><h3>{historyGroups[g]}</h3>{rows.map(c=><Button id={`history-${c.id}`} key={c.id} variant="ghost" onClick={()=>inspect('history',c.id)}><span><strong>{c.title}</strong><span className="record-context">{c.contexts.join(' / ')}</span><span className="record-context">목소리: {c.participants.map(p=>personName(p,state.playerName)).join(' · ')||'아직 없음'}</span></span></Button>)}</section>;})}{!filtered.length&&<p className="empty-note">실제로 지나온 대화에서 조건에 맞는 기록을 찾을 수 없습니다.</p>}</section>;
}

export function PeoplePanel({state,detail,inspect,expanded=[],patch}:Props&{expanded?:string[];patch:(v:Partial<View>)=>void}){
 const record=detail?personRecord(state,detail):null;
 if(detail&&record){const entries=conversations(state).filter(c=>c.participants.includes(detail));return <article className="person-record"><h3 className="detail-title">{personName(detail,state.playerName)}</h3><p>{record.introduction}</p><p className="source-caption">이미 들은 소개·진술과 직접 본 장면입니다. 현재 위치를 추적하는 화면은 아닙니다.</p>
  {record.facts.filter(f=>f.kind==='introduction').map(f=><Excerpt key={f.nodes[0]} section="intro" entry={f.entries[0]} state={state} inspect={inspect}/>)}
  <section className="person-last"><h4>최근 직접 대화·관찰 기록</h4>{record.lastObserved?<><Context entry={record.lastObserved}/><Button id={`person-last-${detail}`} variant="outline" onClick={()=>inspect('history',record.lastObserved!.sceneId)}>{script.scenes[record.lastObserved.sceneId].title} · 대화 원문</Button></>:<p>같은 자리에서 나눈 대화가 아직 기록되지 않았습니다.</p>}<p>이후의 이동이나 현재 위치를 뜻하지 않습니다. 통화·스피커·녹음 속 목소리는 직접 대면으로 세지 않습니다.</p></section>
  {!!record.corrections.length&&<section className="person-corrections"><h4>진술의 변화</h4>{record.corrections.map(c=><article key={c.id}><h5>처음 한 말</h5><Excerpt section={`before-${c.id}`} entry={state.log.find(l=>l.nodeId===c.before)!} state={state} inspect={inspect}/>{c.corrected?<><h5>이후 정정 · 정정된 범위까지</h5><Excerpt section={`after-${c.id}`} entry={state.log.find(l=>l.nodeId===c.after)!} state={state} inspect={inspect}/><Button id={`person-correction-${c.id}`} variant="outline" onClick={()=>inspect('evidence',c.evidence)}>{correctionLabels[c.id]}</Button></>:<p>이 말에 대한 정정은 아직 듣지 않았습니다.</p>}</article>)}</section>}
  {(['observed','relation','limit'] as const).map(kind=>{const facts=record.facts.filter(f=>f.kind===kind);return !!facts.length&&<section key={kind} className={`person-${kind}`}><h4>{{observed:'직접 본 행동·상황',relation:'대화에서 밝힌 관계',limit:'당시 확인하지 못한 범위'}[kind]}</h4>{facts.map(f=><div key={f.nodes.join('-')}>{f.entries.map(e=><Excerpt key={e.nodeId} section={kind} entry={e} state={state} inspect={inspect}/>)}{kind==='relation'&&<div className="task-actions">{f.people.filter(p=>p!==detail).map(p=><Button id={`relation-${f.nodes[0]}-${p}`} key={p} variant="outline" onClick={()=>inspect('people',p)}>{personName(p,state.playerName)} · 인물 기록</Button>)}</div>}</div>)}</section>;})}
  {!!record.related.length&&<section><h4>관련된 보유 자료</h4><div className="task-actions">{record.related.map(e=><Button id={`person-evidence-${e}`} key={e} variant="outline" onClick={()=>inspect('evidence',e)}>{script.evidence[e].title}</Button>)}</div></section>}
  <section className="person-conversations"><h4>실제로 들은 말 · 대화별로 읽기</h4>{entries.map(c=><details key={c.id} open={expanded.includes(c.id)}><summary id={`person-conversation-${c.id}`} onClick={e=>{e.preventDefault();patch({expanded:expanded.includes(c.id)?expanded.filter(id=>id!==c.id):[...expanded,c.id]});}}>{c.title}<span className="record-context">{c.contexts.join(' / ')}</span></summary>{c.entries.filter(l=>recordNode(l).speaker===detail).map((e,index)=><div key={e.nodeId+index} className="person-statement"><Context entry={e}/><p>{recordNode(e).label&&!/^P\d/.test(recordNode(e).label!)&&<strong>{recordNode(e).label}</strong>}{displayText(recordNode(e).text,state.playerName)}</p></div>)}<Button id={`person-conversation-source-${c.id}`} variant="outline" onClick={()=>inspect('history',c.id)}>전체 대화 원문</Button></details>)}</section>
 </article>;}
 return <div className="people-list">{state.met.map(id=><button id={`person-${id}`} key={id} onClick={()=>inspect('people',id)}><img src={portraitPath(id)!} alt="" loading="lazy"/><span>{personName(id,state.playerName)}<small>{personRecord(state,id)?.introduction}</small></span></button>)}</div>;
}
