import {chromium} from '@playwright/test';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const fixtures=JSON.parse(readFileSync('../game-plan/validation/runtime-ep-fixtures.json','utf8'));
const out='../game-plan/validation/ep-browser';mkdirSync(out,{recursive:true});
const browser=await chromium.launch(),results=[];
try{for(const profile of [{name:'desktop',width:1440,height:900,scale:1,touch:false},{name:'phone-200',width:390,height:844,scale:2,touch:true}]){
 const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},hasTouch:profile.touch,isMobile:profile.touch}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173/',{waitUntil:'networkidle'});
 const restore=async f=>{assert.ok(f);await page.evaluate(s=>{localStorage.removeItem('yeowul-saves-v2');localStorage.setItem('yeowul-save-v1',JSON.stringify(s));},{...f,textScale:profile.scale});await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'읽던 자리에서 이어하기',exact:true}).click();};
 const saved=()=>page.evaluate(()=>{const v=JSON.parse(localStorage.getItem('yeowul-saves-v2'));return v.slots.find(s=>s.id===v.active).state;});
 const noOverflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&Array.from(document.querySelectorAll('.tool-dialog,.tool-body')).every(el=>el.scrollWidth<=el.clientWidth+2)),true,profile.name);
 const pass=(group,checks)=>results.push({profile:profile.name,group,status:'pass',checks});
 for(const sound of ['consented_voices','environment_only']){
  await restore(fixtures['choice-B_SOUND']);const name=sound==='consented_voices'?'허락한 사람의 목소리만, 용도를 말하고 새로 받는다.':'이번 과제는 장소 소리만 남긴다.';
  await page.locator('.choice-list').getByRole('button',{name,exact:true}).click();const modes=[],captured=[];
  for(let n=0;n<50;n++){
   const s=await saved();if(s.investigation.completed.includes('ep-sound'))break;
   const mode=await page.locator('[data-recording]').getAttribute('data-recording');modes.push(mode);
   if(mode==='recording')captured.push(await page.locator('.dialogue-text').innerText());
   await page.locator('.dialogue-box').getByRole('button',{name:'계속',exact:true}).click();
  }
  assert.ok(modes.includes('off')&&modes.includes('recording')&&modes.includes('complete'));const s=await saved();assert.equal(s.choices.B_SOUND,sound);assert.equal(s.choices.B_PLAYBACK_RESPONSE,fixtures['choice-B_SOUND'].choices.B_PLAYBACK_RESPONSE);
  if(sound==='consented_voices'){assert.ok(captured.some(t=>t.includes('여울관에는 비 오는 날')));assert.equal(captured.some(t=>t.includes('이번 과제에서는 빼 줘')),false);}else assert.equal(captured.some(t=>t.includes('선생님 목소리')),false);
  await noOverflow();await page.screenshot({animations:'disabled',path:`${out}/${profile.name}-${sound}.png`,fullPage:true});pass(sound,['actual choice played','recorder off during permissions/refusal','only selected recording interval','forgiveness unchanged']);
 }
 await restore(fixtures['choice-B_EXHIBIT']);await page.locator('.choice-list').getByRole('button',{name:'당사자별 공동 주석을 같은 문서 옆에 병기한다.',exact:true}).click();const cursor=(await saved()).cursor;await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'읽던 자리에서 이어하기',exact:true}).click();assert.equal((await saved()).cursor,cursor);assert.match(await page.locator('.dialogue-text').innerText(),/한 문서 옆에/);assert.equal((await saved()).log.some(l=>l.nodeId==='S_EP_03_0051'),false);pass('late exhibit',['stable choice cursor after reload','late branch stays distinct from earlier-choice callback']);
 const end=fixtures['ending-protect_papers-ask_voice_later-need_time-joint_annotations-environment_only-true'];await restore(end);assert.equal(await page.locator('.visit-hint').count(),0);await page.getByRole('button',{name:'사건 보관함 열기',exact:true}).click();const dialog=page.getByRole('dialog');await noOverflow();await page.screenshot({animations:'disabled',path:`${out}/${profile.name}-archive.png`,fullPage:true});
 await dialog.getByRole('button',{name:'증거 보관함',exact:true}).click();assert.equal(await dialog.locator('.evidence-list button').count(),52);await dialog.locator('#evidence-E49').click();await dialog.locator('.evidence-E49').waitFor();await dialog.getByRole('button',{name:'이 자료를 확인한 장면 보기',exact:true}).click();assert.match(await dialog.locator('.history-log').innerText(),/20시 14분|20:14/);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.keyboard.press('Escape');
 await dialog.getByRole('button',{name:'추론 기록',exact:true}).click();assert.equal(await dialog.locator('.archive-card').count(),36);assert.equal(await dialog.locator('.archive-role').count(),5);assert.match(await dialog.locator('.archive-card').last().innerText(),/은폐부터/);await page.keyboard.press('Escape');
 await dialog.getByRole('button',{name:'진술 변화',exact:true}).click();assert.equal(await dialog.locator('.correction-pair').count(),6);await noOverflow();await page.screenshot({animations:'disabled',path:`${out}/${profile.name}-corrections.png`,fullPage:true});await page.keyboard.press('Escape');
 await dialog.getByRole('button',{name:'선택 회고',exact:true}).click();assert.equal(await dialog.locator('.archive-card').count(),5);const recap=await dialog.innerText();assert.match(recap,/자동 화해로 바뀌지/);assert.match(recap,/목소리 허락을 새로 묻지/);assert.doesNotMatch(recap,/해금에게 새 허락을 물었습니다/);await noOverflow();await page.screenshot({animations:'disabled',path:`${out}/${profile.name}-recap.png`,fullPage:true});await page.keyboard.press('Escape');
 await dialog.getByRole('button',{name:'크레딧',exact:true}).click();assert.match(await dialog.innerText(),/ChatGPT/);await page.keyboard.press('Escape');pass('archive controls',['52 actual evidence and acquisition scene','36 submitted deductions and five final roles','six correction pairs','five actual branch recaps only','credits']);
 await dialog.getByRole('button',{name:'대화 기록',exact:true}).click();await dialog.locator('#history-C_EP_04').click();await dialog.getByRole('button',{name:'한 대사씩 다시 읽기',exact:true}).click();const snapshot=await saved();await dialog.getByRole('button',{name:'다음 대사',exact:true}).click();assert.equal((await saved()).views.at(-1).replayIndex,1);await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'읽던 자리에서 이어하기',exact:true}).click();assert.equal((await saved()).views.at(-1).replayIndex,1);assert.deepEqual((await saved()).log,snapshot.log);assert.deepEqual((await saved()).choices,snapshot.choices);assert.deepEqual((await saved()).investigation,snapshot.investigation);await noOverflow();pass('history replay',['only encountered lines','replay cursor restored','no knowledge, choices or log mutations']);
 await dialog.getByRole('navigation',{name:'다른 조사 도구'}).getByRole('button',{name:'설정',exact:true}).click();await dialog.getByRole('button',{name:'지금 저장하기',exact:true}).click();await dialog.getByRole('status').waitFor();const endingSaved=await saved();await dialog.getByRole('button',{name:'새 슬롯에서 처음부터',exact:true}).click();assert.equal((await saved()).sceneId,'C_PR_01');
 let store=await page.evaluate(()=>JSON.parse(localStorage.getItem('yeowul-saves-v2')));assert.equal(store.slots.length,2);assert.equal(store.slots[0].state.investigation.completed.includes('ep-archive'),true);assert.deepEqual(store.slots[0].state.choices,endingSaved.choices);assert.deepEqual(store.slots[0].state.investigation.drafts.D30,endingSaved.investigation.drafts.D30);
 await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:/1\. .* · 엔딩/}).click();assert.equal((await saved()).sceneId,'C_EP_06');store=await page.evaluate(()=>JSON.parse(localStorage.getItem('yeowul-saves-v2')));assert.equal(store.slots.length,2);await noOverflow();pass('persistent slots',['legacy migration','manual ending save','restart in separate slot','ending and final proof retained','ending selected after reload']);
 for(let n=0;n<5;n++){await page.keyboard.press('Tab');assert.ok(await page.getByRole('dialog').evaluate(el=>el.contains(document.activeElement)));}
 assert.deepEqual(errors,[]);pass('accessibility',['desktop or touch200%','no horizontal overflow','keyboard contained in modal','no page errors']);await context.close();
 }writeFileSync(`${out}/results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close();}
