import {chromium} from '@playwright/test';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const fixtures=JSON.parse(readFileSync('../game-plan/validation/runtime-ep-fixtures.json','utf8'));
const out='../game-plan/validation/records-browser';mkdirSync(out,{recursive:true});
const browser=await chromium.launch(),results=[];
try{for(const profile of [{name:'desktop',width:1440,height:900,scale:1,touch:false},{name:'phone-200',width:390,height:844,scale:2,touch:true}]){
 const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},hasTouch:profile.touch,isMobile:profile.touch}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173/',{waitUntil:'networkidle'});
 const restore=async f=>{assert.ok(f);await page.evaluate(s=>{localStorage.removeItem('yeowul-saves-v2');localStorage.setItem('yeowul-save-v1',JSON.stringify(s));},{...f,textScale:profile.scale});await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'읽던 자리에서 이어하기',exact:true}).click();};
 const saved=()=>page.evaluate(()=>{const v=JSON.parse(localStorage.getItem('yeowul-saves-v2'));return v.slots.find(s=>s.id===v.active).state;});
 const dialog=page.getByRole('dialog'),nav=dialog.getByRole('navigation',{name:'다른 조사 도구'});
 const noOverflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&Array.from(document.querySelectorAll('.tool-dialog,.tool-body')).every(el=>el.scrollWidth<=el.clientWidth+2)),true,profile.name);
 const capture=async name=>{await noOverflow();await page.screenshot({animations:'disabled',path:`${out}/${profile.name}-${name}.png`,fullPage:true});};
 const pass=(group,checks)=>{results.push({profile:profile.name,group,status:'pass',checks});console.log(profile.name,group,'pass');};
 await restore(fixtures['task-D01']);await nav.getByRole('button',{name:'인물',exact:true}).click();assert.equal(await dialog.locator('#person-P06').count(),0);await capture('people');await dialog.locator('#person-P04').click();assert.match(await dialog.locator('.person-record').innerText(),/건물 수리 담당/);assert.doesNotMatch(await dialog.locator('.person-record').innerText(),/제 사촌|범인|은폐한/);await capture('introduction');
 await page.keyboard.press('Escape');await dialog.locator('#person-P08').click();assert.match(await dialog.locator('.person-last').innerText(),/앉지 않는 사람/);assert.doesNotMatch(await dialog.locator('.person-last').innerText(),/사람 없이 들린 안내/);pass('introduced people',['met-only list','role after heard introduction','no future cousin or guilt labels','speaker output excluded from last direct contact']);
 await nav.getByRole('button',{name:'대화',exact:true}).click();assert.equal(await dialog.locator('#history-group option[value="ending"]').count(),0);await dialog.locator('#history-speaker').selectOption('P08');await dialog.locator('#history-C_PR_14').click();assert.match(await dialog.locator('.history-log').innerText(),/공식 안내 출력/);assert.doesNotMatch(await dialog.locator('.history-log').innerText(),/리허설 파일|재생 버튼/);await capture('early-output');pass('early history',['heard-only groups/speakers','public voice attributed without early playback answer','full actual source transcript']);
 const end=fixtures['ending-protect_papers-ask_voice_later-need_time-joint_annotations-environment_only-true'];assert.ok(end.log.every(l=>l.origin),'Regenerate EP fixtures after record-origin integration');await restore(end);await page.getByRole('button',{name:'사건 보관함 열기',exact:true}).click();await nav.getByRole('button',{name:'대화',exact:true}).click();await dialog.locator('#history-group').selectOption('ending');await dialog.locator('#history-speaker').selectOption('P01');const count=await dialog.locator('.history-group button').count();assert.ok(count>0&&count<6);await capture('filtered-history');
 await dialog.locator('#history-C_EP_04').click();assert.match(await dialog.locator('.history-log').innerText(),/10월 23일/);assert.match(await dialog.locator('.history-log').innerText(),/음향 부스/);await dialog.getByRole('button',{name:'한 대사씩 다시 읽기',exact:true}).click();await dialog.getByRole('button',{name:'다음 대사',exact:true}).click();const replaySaved=await saved();await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'읽던 자리에서 이어하기',exact:true}).click();assert.equal((await saved()).views.at(-1).replayIndex,1);assert.deepEqual((await saved()).log,replaySaved.log);await page.keyboard.press('Escape');assert.equal(await dialog.locator('#history-group').inputValue(),'ending');assert.equal(await dialog.locator('#history-speaker').inputValue(),'P01');pass('history filters and replay',['combined group and speaker','actual contextual dates/places','replay cursor saved','no log effects','filters restored after detail']);
 await nav.getByRole('button',{name:'인물',exact:true}).click();await dialog.locator('#person-P09').click();assert.match(await dialog.locator('.person-corrections').innerText(),/복사하는 내내/);assert.match(await dialog.locator('.person-corrections').innerText(),/제 손에 돌려받지/);await dialog.locator('#person-correction-Q06').click();await dialog.locator('.evidence-E52').waitFor();await dialog.getByRole('button',{name:'이 자료를 확인한 장면 보기',exact:true}).click();await dialog.locator('.history-log').waitFor();await page.keyboard.press('Escape');await page.keyboard.press('Escape');
 await dialog.locator('#person-conversation-C_CH06_01').click();assert.equal(await dialog.locator('#person-conversation-C_CH06_01').evaluate(e=>e.parentElement.open),true);await dialog.locator('#person-conversation-source-C_CH06_01').click();assert.match(await dialog.locator('.history-log').innerText(),/통화로 들은 말/);assert.match(await dialog.locator('.history-log').innerText(),/읍내 게스트하우스/);await capture('remote-origin');await page.keyboard.press('Escape');await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'읽던 자리에서 이어하기',exact:true}).click();assert.equal(await dialog.locator('#person-conversation-C_CH06_01').evaluate(e=>e.parentElement.open),true);pass('person correction and source expansion',['both heard Q06 versions','correction/source links','phone caller distinguished from listener location','expanded conversation retained on reload']);
 await nav.getByRole('button',{name:'인물',exact:true}).click();await dialog.locator('#person-P06').click();assert.match(await dialog.locator('.person-relation').innerText(),/제 사촌/);await dialog.locator('#relation-S_CH03_01_0005-P04').click();assert.match(await dialog.locator('.person-record').innerText(),/탁두철/);await dialog.locator('.person-observed').scrollIntoViewIfNeeded();await capture('observed-actions');pass('sourced relationships',['only encountered relation excerpts','bidirectional related-person navigation','direct actions separated from attributed speech']);
 const old=structuredClone(end);old.log.forEach(l=>delete l.origin);await restore(old);await page.getByRole('button',{name:'사건 보관함 열기',exact:true}).click();await nav.getByRole('button',{name:'인물',exact:true}).click();await dialog.locator('#person-P08').click();assert.match(await dialog.locator('.person-last').innerText(),/당시 장소 미기록/);assert.match(await dialog.locator('.person-last').innerText(),/앉지 않는 사람/);pass('legacy history',['old log without origins loads','missing position stated explicitly','no present location invented']);
 await restore(fixtures['task-D30']);await dialog.locator('.proof-note textarea').last().fill('마지막 연결은 그대로 두고 기록 확인');const before=await saved();await nav.getByRole('button',{name:'대화',exact:true}).click();await dialog.locator('#history-group').selectOption('challenge');await dialog.locator('#history-speaker').selectOption('P09');await dialog.locator('#history-search').fill('복사');await dialog.locator('#history-C_Q06').click();await dialog.locator('#history-correction-Q06').click();await dialog.locator('#source-E52-P09').click();await nav.getByRole('button',{name:'지도',exact:true}).click();await noOverflow();for(let i=0;i<4;i++)await page.keyboard.press('Escape');assert.equal(await dialog.locator('#history-search').inputValue(),'복사');assert.equal(await dialog.locator('#history-speaker').inputValue(),'P09');await page.keyboard.press('Escape');const after=await saved();assert.deepEqual(after.investigation,before.investigation);assert.deepEqual(after.log,before.log);assert.deepEqual(after.choices,before.choices);assert.equal(after.points,before.points);pass('answer round trip',['D30 actual edited draft','filtered history → correction → person → map → history → answer','same task/draft/log/choices/points']);
 await nav.getByRole('button',{name:'대화',exact:true}).click();await dialog.locator('#history-group').focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.notEqual(await dialog.locator('#history-group').inputValue(),'');for(let n=0;n<5;n++){await page.keyboard.press('Tab');assert.ok(await dialog.evaluate(e=>e.contains(document.activeElement)));}assert.ok(await dialog.locator('select').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)));await noOverflow();assert.deepEqual(errors,[]);pass('keyboard and layout',['native keyboard filter selection','Tab contained','44px selectors','desktop or touch200% no horizontal overflow','no page errors']);await context.close();
 }writeFileSync(`${out}/results.json`,JSON.stringify(results,null,2));console.log(`${results.length} browser record groups passed`);
}finally{await browser.close();}
